name: keyword_extractor
description: A lightweight Dart package that extracts keywords from class instances via toMap/toJson. Ideal for building simple full-text search or tagging systems..
version: 0.0.1
repository: https://github.com/plokmij/keyword_extractor

environment:
  sdk: ^3.7.2

dependencies:

dev_dependencies:
  lints: ^5.0.0
  test: ^1.24.0
