name: keyword_extractor
description: A lightweight Dart package that extracts keywords from class instances via toMap/toJson. Ideal for building simple full-text search or tagging systems..
version: 0.0.1
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.7.2

# Add regular dependencies here.
dependencies:
  # path: ^1.8.0

dev_dependencies:
  lints: ^5.0.0
  test: ^1.24.0
